wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1665474570.804762
    t:
      1:
      - 55
      3:
      - 13
      - 23
      4: 3.9.12
      5: 0.13.3
      8:
      - 1
      - 5
